### ISSUE TITLE
Indentation uses tabulations but guidelines suggest against this

### ISSUE THREAD

**Issue by ArwynFr** [th3-sh0w3r/VSCode-SQF-Formatter#2]
When formatting a document, the extension will indent using a tabulation.
However ACE guidelines says:
> Indentations consist of 4 spaces. Tabs are not allowed.

Source : https://ace3.acemod.org/wiki/development/coding-guidelines.html#52-indents

**Comment by th3-sh0w3r** [comment]
If you wanna change that you can make pull request.
I will not change that because this depends on the IDE and the user preference.
I'm using VSCode and for it looks fine there.

**Comment by Napster653** [comment]
Is there any chance this could be configurable in the extension settings?
